image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn
  - yarn install
  #- yarn add -g npm@5.4.2
  - yarn add electron-forge -g

build_script:
  - yarn make

test: off